### PR TITLE
Update week 1 schedule with link to new design burst slides

### PR DESCRIPTION
**Pull request by bobbysebolao**
**Link:** http://facresources.com/

See new slides for the week 1 design bust under the 'Design burst' section.

Feedback welcome!

### CODE REVIEW

**Comment by oliverjam** [comment]
I had no idea that website existed. Is there any reason this can't just be a markdown file in the Coursebook that links to all the slides? It feels a bit weird to direct people to a different site entirely

**Comment by bobbysebolao** [comment]
The link I added to the schedule goes straight to the slide deck. The markdown file you're referring to lives in the [fac-slide-kit](https://github.com/foundersandcoders/fac-slide-kit/blob/master/index.md) repo. Any time time you update that readme, the facresources.com page auto updates, I'm not sure where it's deployed though.

**Comment by oliverjam** [comment]
Yeah I guess directly linking to them is fine. Any reason we aren't just using HackMD for these? I feel like I'm missing historical context for what this resource site is for.

**Comment by bobbysebolao** [comment]
fac-slide-kit is forked from reveal.js, I think Michael created the custom FAC-styling for the slides in that repo. I think it's so that the slide decks are formatted consistently, which you can't do with HackMD

**Pull request merged**
