### PR TITLE
Re-organise curriculum for FAC22/23

### LINKED ISSUE #504: Revisiting the pre-apprenticeship curriculum
We'll wrap up delivery of our first iteration of the pre-apprenticeship in w/c 30 Aug. We're due to start delivering the curriculum again from w/c 27 September. The time between, we're due to be offline. 

Before we finish up delivery of the first iteration, it'd be useful to revisit the programme and think about the structure and content for the second iteration including consideration of FAC22's feedback. Either in a working group reporting back to CC or in CC itself.

### PR DESCRIPTION
**Pull request by oliverjam**
- [x] Set new pre-apprenticeship schedules (with each topic spread over 3 part-time weeks)
- [x] Divide syllabus into `/pre-apprenticeship` and `/apprenticeship` (keeps the nav cleaner)
- [x] Delete unused old schedules
- [x] Clean up timetable design
- [x] Clean up Semantic HTML and CSS workshops for Week 1

## New pre-apprenticeship schedules

Screenshot 2021-09-22 at 16 01 01

## Apprenticeship timetable design tweak

Screenshot 2021-09-22 at 16 00 53

Fix #504

### CODE REVIEW

**Comment by sofer** [comment]
There's a lot of material to review! Initial question: have we got all 5 parts of the series on managing software projects in there somewhere https://hackmd.io/@fac/S1wGfV2M8#/1?

**Comment by oliverjam** [comment]
@sofer no this is literally just pure curriculum right now (i.e. a list of the workshops/projects we expect them to complete each week). If we want to also document talks/other material that will be delivered to them that can probably go in a separate PR

**Comment by oliverjam** [comment]
It's probably easier to review the content in the deployed preview btw
https://deploy-preview-511--fac-coursebook.netlify.app/course/syllabus/pre-apprenticeship/teamwork/schedule/

**Comment by Albadylic** [comment]
Looks great, thanks for doing all this. ✨ 

for Markup there are broken links for spikes and projects, did we want them to work on the ones listed in Teamwork? This is maybe just a naming thing

**Comment by oliverjam** [comment]
@Albadylic good catch, forgot to move spikes over yeah. I'll fix now

**Review by Albadylic — APPROVED** [review]
Fantastic 🎉

**Pull request merged**
