### PR TITLE
Add week 2 "Real world fetch" workshop

### LINKED ISSUE #35: Submitting data with fetch
How to `POST` data with fetch.

- URLencoded & JSON
- Different ways to access form values
    1. Directly accessing `querySelector("#my-input").value`
    1. Using `event.target.elements[name].value`
    1. `Object.fromEntries(new FormData(form))`

### PR DESCRIPTION
**Pull request by oliverjam**
https://github.com/oliverjam/real-world-fetch

- Covers stuff you need to use `fetch` in a real app
    - Error handling for non-200 HTTP responses
    - `fetch` options:
        - method
        - body
- Handling user input with forms
    - `preventDefault()`
    - Various ways to access form input data

I'm not sure if it needs a proper "workshop" bit at the end. Some of the interspersed "challenges" are more involved and are basically what I'd want from a "workshop" anyway.

I also swapped the first-class functions and learn-fetch-promises workshops around, since we should cover callbacks before promises.

Closes #35

### CODE REVIEW

**Comment by bobbysebolao** [comment]
I ran through this and I think it's really good. I think you're right that the challenges throughout are involved enough to make this feel like a workshop with enough chances for students to practice the concepts that are covered for themselves 👍

**Comment by Albadylic** [comment]
p.s. I definitely learnt a couple of things from reading this!

**Comment by oliverjam** [comment]
@Albadylic cheers, fixed that bit. I think it could still do with a "workshop" part at the end because this is supposed to fill 2 hours. It's currently a 5 or 6 minute read (obviously longer with all the breaks to do the code challenges/let stuff sink in). It would be nice for people who have done some fetch before and whizz through the simpler parts to be able to push themselves a bit.

**Comment by Albadylic** [comment]
@oliverjam Yeah, I reckon this would benefit from a workshop section to fill the two hours. It could be very similar to the challenges, as in the learn-fetch workshop, but on a new api - something that is likely to 404.

**Comment by oliverjam** [comment]
@Albadylic I've added a simple-ish workshop at the end using the same PokéAPI they used in the first fetch workshop. This time they actually have to make a form and render to the page, plus handle errors.

**Comment by Albadylic** [comment]
Anytime you use the PokeAPI, you get my automatic approval.

**Pull request merged**
