### PR TITLE
Week 4 schedule

### LINKED ISSUE #43: Node intro
- Check Node is installed (and at least LTS version)
- Quick overview of running JS in your terminal with the `node` repl
- Quick overview of running a JS file with `node file.js`
- Quick look at starting a server with `http`

### PR DESCRIPTION
**Pull request by oliverjam**
I got carried away writing a quick intro to Node and ended up writing a pretty much complete guide to Node 😅 

1. Node Introduction: wtf is Node, how do I install it, how do I run it, what's a `require`?
    https://github.com/oliverjam/node-introduction
1. Node HTTP Servers: creating a web server, routes, 404s
    https://github.com/oliverjam/node-http-server
1. Node File Servers: `fs`, reading and serving files, error-first callbacks, `content-type`s
    https://github.com/oliverjam/node-file-server

Also some scheduling changes: spike research moved to Monday afternoon, with presentations on Tuesday morning. Tech For Better moves to Tuesday afternoon (although it probably isn't happening this cohort)

Fixes #43

### CODE REVIEW

**Comment by sofer** [comment]
My only thought: 09:45 is now a check-in. This may be something that is appropriate for both on-line and off-line classrooms. it's a bit like taking the register ;-)

**Comment by oliverjam** [comment]
@sofer Yeah I guess that applies to all weeks. Do we drop the morning reading then? It's been kind of inconsistent anyway—we set some when we think of it/have something good for them to read

**Comment by edificex** [comment]
@oliverjam does this all replace the Node Girls workshop?

**Comment by oliverjam** [comment]
@edificex yup. I wasn't planning on it but I got carried away and ended up covering all the same material. I just need to add a bit on handling POST body streams to the HTTP Server workshop

**Comment by oliverjam** [comment]
@sofer @Albadylic I've made the scheduling changes we discussed on Friday. Are you happy with them?

**Comment by sofer** [comment]
Renamed the 09:45 slots. Happy for this to be merged.

**Pull request merged**
